[build]
  command = "npm run build"  # Adjust this to match your build command
  functions = "functions"    # Directory where Netlify functions are located

[dev]
command = "npm run start:dev"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api.js"
  status = 200
